pub mod cli;
pub mod commands;
pub mod config;
pub mod contracts;
pub mod docs;
pub mod embed;
pub mod exec;
pub mod federated;
pub mod gemini;
pub mod git;
pub mod impact;
pub mod index;
pub mod ledger;
pub mod local_model;
pub mod observability;
pub mod output;
pub mod platform;
pub mod policy;
pub mod retrieval;
pub mod state;
pub mod util;
pub mod verify;
pub mod watch;

#[cfg(feature = "daemon")]
pub mod daemon;
